# Generated by Django 4.2.5 on 2023-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_alter_assignment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studname', models.CharField(max_length=255)),
            ],
        ),
    ]
