# Generated by Django 4.2.5 on 2023-10-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
